import pathlib

out = pathlib.Path("/Users/f00421k/Documents/GitHub/national-association-visual-arts/docs/presentation.html")

slides = []

def fig(label, title, img, caption=""):
    return f'''
      <section style="background:#fff;">
        <p class="label">{label}</p>
        <h2>{title}</h2>
        <img src="figures/{img}" style="width:100%;max-width:960px;display:block;margin:0.8em auto 0;">
        {f'<p class="cap">{caption}</p>' if caption else ''}
      </section>'''

def quote(label, title, text, attr):
    return f'''
      <section>
        <p class="label">{label}</p>
        <h2>{title}</h2>
        <blockquote>
          <p>{text}</p>
          <footer>{attr}</footer>
        </blockquote>
      </section>'''

def stat_slide(label, title, desc, stats):
    cards = ""
    for n, u in stats:
        cards += f'<div class="card"><span class="big">{n}</span><span class="unit">{u}</span></div>\n'
    return f'''
      <section>
        <p class="label">{label}</p>
        <h2>{title}</h2>
        <p class="desc">{desc}</p>
        <div class="row">{cards}</div>
      </section>'''

def dark(label, title, body=""):
    return f'''
      <section class="dark">
        <p class="label">{label}</p>
        <h2>{title}</h2>
        {body}
      </section>'''

# BUILD SLIDES
slides.append('''
      <section class="title-slide">
        <p class="label">NAVA Research &middot; 2025</p>
        <h1>AI &amp; Visual Arts Practice</h1>
        <p class="sub">What 890 Australian creative practitioners told us about generative AI</p>
        <div class="author">
          <strong>Charles Crabtree</strong><br>
          Senior Lecturer, School of Social Sciences, Monash University<br>
          K-Club Professor, University College, Korea University
        </div>
      </section>''')

slides.append(stat_slide("Overview", "A community at a crossroads",
    "The largest survey of Australian visual artists on generative AI to date.",
    [("890","respondents"), ("85%","visual artists &amp; craftspeople"), ("28%","regional or remote")]))

slides.append(fig("Who Responded", "85% are visual artists or craftspeople",
    "fig01_practitioner_type.png"))

slides.append(fig("Identity", "28% live regionally or remotely",
    "fig02_identity.png"))

slides.append(fig("Adoption", "46% of creative practitioners use generative AI",
    "fig03_ai_adoption.png"))

slides.append(fig("What For", "Editing and drafting dominate\u2014only 6% use AI for final artwork",
    "fig04_ai_uses.png"))

slides.append(fig("Motivation", "Saving time is the primary driver (36%)",
    "fig05_main_reason.png"))

slides.append(quote("In Their Words", "Time-poor arts workers find efficiency",
    "For underfunded and time poor arts workers, AI can be enormously helpful in cutting down time for certain tasks\u2026 AI has helped to not only make that workload more manageable, but also to provide a springboard for tasks which are unfamiliar or outside of existing expertise.",
    "Survey Respondent, Q12"))

slides.append(fig("Usage", "81% say AI influences less than 10% of their final work",
    "fig06_ai_influence_pct.png"))

slides.append(fig("Positives", "Time savings lead, but 32% report no positive impact",
    "fig07_positive_impacts.png"))

slides.append(dark("The Other Side", "71% don\u2019t know if their work was used to train AI",
    '<img src="figures/fig08_unauthorized_use.png" style="width:100%;max-width:900px;display:block;margin:1em auto 0;border-radius:6px;">'))

slides.append(fig("Response", "36% who discovered unauthorized use did nothing",
    "fig09_response_to_misuse.png"))

slides.append(quote("In Their Words", "\u201cSingle artist does not have the legal buying power\u201d",
    "Your work can be taken, anytime, anywhere. AI runs in background, 24hrs/365days. Large companies pilfer ideas. Change colours or shapes. There is no recompense for original artist. Single artist does not have the legal \u2018buying power\u2019 of a business or corporation.",
    "Survey Respondent, Q19"))

slides.append(fig("Economic Impact", "38% report reduced trust in originality",
    "fig10_income_impacts.png"))

slides.append(quote("Lost Commissions", "\u201cI am planning on changing careers\u201d",
    "I am a photographer and photo editor and have lost clients to places that offer AI editing. I cannot compete with the prices\u2026 I have lost enough work and find it harder to find new clients that I am planning on changing careers.",
    "Survey Respondent, Q19"))

slides.append(fig("Barriers", "Platform opacity is the #1 barrier (76%)",
    "fig13_barriers.png"))

slides.append(fig("Transparency", "85% want visible \u2018generated by AI\u2019 labelling",
    "fig11_transparency.png"))

slides.append(fig("Disclosure", "71% say AI content should always be disclosed",
    "fig12_disclosure_contexts.png"))

slides.append(fig("Regulation", "69% support a Code of Practice",
    "fig14_regulation.png"))

slides.append(fig("Compensation", "73% support compensation when their work trains AI",
    "fig15_compensation.png"))

slides.append(fig("Licensing", "50% are unsure\u2014an education opportunity",
    "fig16_collective_licensing.png"))

slides.append(fig("Platforms", "ChatGPT dominates: mentioned by 60%",
    "fig17_platform_usage.png"))

slides.append(fig("Themes", "Admin utility and IP concerns dominate open-text responses",
    "fig18_thematic_analysis.png"))

slides.append(quote("Existential Fear", "\u201cIt feels pointless\u201d",
    "I feel that AI can create something in a few seconds, that would take me months to create. So I feel less motivated to make art. It feels pointless.",
    "Survey Respondent, Q19"))

slides.append(quote("Cultural Concerns", "\u201cAI cannot reproduce my culture\u2019s art form\u201d",
    "I am a modern Celtic fine artist. People are using AI to generate Celtic art. AI cannot reproduce my culture\u2019s art form, it looks like spaghetti vomit. It misrepresents Celtic art in every way. Celtic art is an old cultural art form with rules and traditions.",
    "Survey Respondent, Q19"))

slides.append(quote("Indigenous Voices", "First Nations concerns",
    "It is already hard enough for genuine First Nations artists to get our art out there without adding AI or digitally created work to the mix. In my opinion all digital works AI or otherwise are not genuine art. In particular anything that is AI generated.",
    "Survey Respondent, Q4"))

slides.append(quote("Opportunity", "Some see creative potential",
    "I love the opportunities AI offers\u2026 none offer the sort of possibilities that AI delivers. The trick is to make it work FOR you, to make it your own creative tool that can transform but maintain your own creative signature.",
    "Survey Respondent, Q19"))

slides.append(dark("Takeaways", "A community demanding recognition, protection, and choice",
    '''<div class="row" style="margin-top:1.6em;">
          <div class="card dark-card"><strong>IP Protection</strong><br>Disclosure, consent, and compensation when work trains AI.</div>
          <div class="card dark-card"><strong>Regulation</strong><br>Voluntary guidelines are insufficient. Artists want enforceable codes.</div>
          <div class="card dark-card"><strong>Creative Autonomy</strong><br>AI as efficiency tool, not replacement for human authorship.</div>
        </div>'''))

slides.append('''
      <section class="dark end">
        <h2>Thank you</h2>
        <p class="desc" style="color:#b0b0c0;">Data and analysis available at the project repository</p>
        <div class="author" style="border-top-color:rgba(255,255,255,0.12);margin-top:2.5em;">
          <strong style="color:#fff;font-size:1.3em;">Charles Crabtree</strong><br>
          <span style="font-family:'IBM Plex Mono',monospace;letter-spacing:0.04em;opacity:0.7;">charles.crabtree@monash.edu &middot; charlescrabtree.org</span>
        </div>
      </section>''')

all_slides = "\n".join(slides)

html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>NAVA AI &amp; Visual Arts Survey 2025</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reset.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{{box-sizing:border-box}}

.reveal,.reveal .slides section{{
  font-family:'IBM Plex Sans',sans-serif;
  color:#1a1a2e;
  text-align:left;
  background:#fafafa;
}}

.reveal h1,.reveal h2{{
  font-family:'DM Serif Display',serif;
  font-weight:400;
  color:#1a1a2e;
  text-transform:none;
  letter-spacing:-0.02em;
  line-height:1.15;
  margin:0 0 0.5em;
}}
.reveal h1{{font-size:2.8em;}}
.reveal h2{{font-size:1.9em;}}

.reveal p{{font-size:1.1em;line-height:1.55;color:#3a3a52;margin-bottom:0.8em;}}

.label{{
  font-family:'IBM Plex Mono',monospace;
  text-transform:uppercase;
  letter-spacing:0.18em;
  font-size:0.6em !important;
  font-weight:600;
  color:#6366f1;
  margin-bottom:0.8em !important;
  display:inline-block;
}}

.cap{{
  font-size:0.78em !important;
  color:#8888a0 !important;
  margin-top:0.6em !important;
  text-align:center;
}}

.desc{{font-size:1.05em;color:#5a5a72;}}

.sub{{
  font-size:1.3em !important;
  color:#6b6b80 !important;
  margin-top:0.4em !important;
  font-weight:400;
  max-width:700px;
}}

.row{{
  display:flex;
  gap:1.8em;
  margin-top:1.4em;
}}

.card{{
  flex:1;
  background:rgba(255,255,255,0.85);
  border:1px solid #e8e8f0;
  border-radius:12px;
  padding:1.6em;
  text-align:left;
}}

.big{{
  font-family:'DM Serif Display',serif;
  font-size:3.2em;
  color:#4f46e5;
  display:block;
  line-height:1;
  margin-bottom:0.15em;
}}

.unit{{
  font-family:'IBM Plex Mono',monospace;
  font-size:0.7em;
  text-transform:uppercase;
  letter-spacing:0.1em;
  color:#8888a0;
  font-weight:600;
}}

blockquote{{
  background:#f3f2ff;
  border-left:4px solid #6366f1;
  padding:1.4em 2em;
  margin:1.2em 0;
  border-radius:0 10px 10px 0;
}}
blockquote p{{
  font-style:italic;
  font-size:1.05em;
  color:#2a2a42;
  margin:0;
  line-height:1.65;
}}
blockquote footer{{
  margin-top:0.8em;
  font-style:normal;
  font-size:0.8em;
  color:#8888a0;
  font-family:'IBM Plex Mono',monospace;
}}

/* Figure slides */
section[style*="background:#fff"] img{{
  border-radius:6px;
  box-shadow:0 4px 24px rgba(0,0,0,0.06);
}}

/* Dark slides */
.dark{{
  background:#12121f !important;
  color:#e8e8f0 !important;
}}
.dark h2{{color:#f0f0f8 !important;}}
.dark p,.dark .desc{{color:#b0b0c8 !important;}}
.dark .label{{color:#a5b4fc !important;}}
.dark-card{{
  background:rgba(255,255,255,0.06) !important;
  border-color:rgba(255,255,255,0.1) !important;
  color:#d0d0e0 !important;
}}
.dark-card strong{{color:#c7d2fe;display:block;margin-bottom:0.4em;font-size:1.1em;}}

/* Title slide */
.title-slide{{
  background:linear-gradient(160deg,#0f0f1a 0%,#1a1a35 40%,#252550 100%) !important;
}}
.title-slide h1{{color:#fff !important;font-size:3.2em;}}
.title-slide .label{{color:#818cf8 !important;}}
.title-slide .sub{{color:#a0a0c0 !important;}}

.author{{
  font-size:0.72em !important;
  color:#9090a8 !important;
  margin-top:3em !important;
  border-top:1px solid rgba(150,150,180,0.2);
  padding-top:1.2em;
}}
.title-slide .author{{color:#8080a0 !important;}}
.title-slide .author strong{{color:#d0d0e8;}}

.end h2{{color:#fff !important;text-align:center;font-size:2.4em;}}
.end .desc{{text-align:center;}}
.end .author{{text-align:center;}}

/* Progress bar */
.reveal .progress{{height:3px;}}
.reveal .progress span{{background:linear-gradient(90deg,#6366f1,#8b5cf6,#a78bfa);}}
.reveal .slide-number{{font-family:'IBM Plex Mono',monospace;font-size:0.6em;color:#aaa;}}
</style>
</head>
<body>
<div class="reveal">
<div class="slides">
{all_slides}
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.js"></script>
<script>
Reveal.initialize({{
  hash:true,
  center:false,
  progress:true,
  slideNumber:'c/t',
  transition:'fade',
  transitionSpeed:'fast',
  controls:true,
  margin:0.06,
  width:1280,
  height:720
}});
</script>
</body>
</html>'''

out.write_text(html, encoding='utf-8')
print(f"Written {len(html):,} bytes to {out}")
